### PR TITLE
Bump Dockerfile to Focal

### PR DESCRIPTION
**Pull request by mvdkleijn**

### CODE REVIEW

**Comment by james-pollard-leapyear** [comment]
@clarafu @vito any plan to merge this?

**Comment by mvdkleijn** [comment]
By now this should probably be jammy...

**Comment by vito** [comment]
I'm not really involved in this anymore, maybe @xtremerui would know how best to integrate this change into our pipelines. :slightly_smiling_face:

**Comment by xtremerui** [comment]
we are indeed transitioning to jammy. @mvdkleijn if you change it to jammy we should be able to merge it.

**Comment by xtremerui** [comment]
Close as change being done

**Pull request closed without merging**
